---
- hosts: masters
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Verify Connectivity
      command: kubeadm config images pull

    - name: Kubeadm init
      command: kubeadm init --pod-network-cidr=10.244.0.0/16

    - file:
        path: /home/ubuntu/.kube
        state: directory
        owner: ubuntu
        group: ubuntu

    - name: Copy conf
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        remote_src: yes
        owner: ubuntu

    - name: Download rbac canal
      get_url:
        url: https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/hosted/canal/rbac.yaml
        dest: /home/ubuntu/canal-rbac.yml 

    - name: Download canal
      get_url:
        url: https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/hosted/canal/canal.yaml
        dest: /home/ubuntu/canal.yml 

    - name: Install rbac canal
      command: kubectl apply -f /home/ubuntu/canal-rbac.yml 
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

    - name: Install pod Network
      command: kubectl apply -f /home/ubuntu/canal.yml 
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
