---
apiVersion: kubeadm.k8s.io/v1beta1
kind: JoinConfiguration
discovery:
  bootstrapToken:
    token: TOKEN
    apiServerEndpoint: "kubernetes.k8s.devopxlabs.com:6443"
    caCertHashes:
      - "sha256:HASH"
nodeRegistration:
  name: HOSTNAME
  kubeletExtraArgs:
    cloud-provider: aws
